### ISSUE TITLE
Python3(.5) support

### ISSUE THREAD

**Issue by Don42** [UmSenhorQualquer/pyforms#13]
Hi,
the documentation is ambiguous, does pyforms actually support python 3 or not?
On the top of the documentation there is the following paragraph:

> Pyforms is a Python 2.7.x and 3.x cross-enviroment framework to develop GUI applications, which promotes modular software design and code reusability with minimal effort.

But later it lists only python3 in the dependencies.

**Comment by cajomferro** [comment]
Hello,

Thank you for giving pyForms a try and leaving your feedback!

Short answer to your question: Yes! It supports python3(.5). I have several projects in python 3.5 with pyForms.

Long answer: Since pyForms is composed of several Controls, it is not guaranteed that all of them will fully support python 3.5.

I'll update the documentation as soon as possible to make it more clear.

Greetings!

**Comment by UmSenhorQualquer** [comment]
Now it is supported
